### PR TITLE
Wishlist

### PR DESCRIPTION
**Pull request by varnita619**
- added wishlist page

### CODE REVIEW

**Comment by pritam-kr** [comment]
Looks clean...And you can improve those things as we discussed.

**Comment by sharathnair9999** [comment]
Looks good to me. You need to fix the horizontal scroll bug. Rest is good

**Review by pritam-kr — APPROVED** [review]

**Review by samyakshah3008 — APPROVED** [review]
Perfect, ready to merge!

**Review by romabulani — APPROVED** [review]
Good to merge

**Pull request merged**
