### PR TITLE
feat : added, login, logout, sign-up page

### PR DESCRIPTION
**Pull request by varnita619**
-added sign-up
- login
- logout page

### CODE REVIEW

**Review by pritam-kr — APPROVED** [review]

**Comment by shrey27** [comment]
Check the cart page and products page again. under 400px both these pages are breaking. I can see oversized components and overflowing of content.

**Review by shrey27 — APPROVED** [review]

**Review by Aman-Jain1996 — APPROVED** [review]
SignUp link is not working in login page ,
Suggestion - hide login button from navbar when on login page ,
Suggestion - Home page shop now button is a CTA button , style it different and more appealing than any other button on the page to catch user attention

**Comment by varnita619** [comment]
> SignUp link is not working in login page , Suggestion - hide login button from navbar when on login page , Suggestion - Home page shop now button is a CTA button , style it different and more appealing than any other button on the page to catch user attention



> SignUp link is not working in login page , Suggestion - hide login button from navbar when on login page , Suggestion - Home page shop now button is a CTA button , style it different and more appealing than any other button on the page to catch user attention

Made all the changes

**Comment by varnita619** [comment]
> Check the cart page and products page again. under 400px both these pages are breaking. I can see oversized components and overflowing of content.  

Made the changes

**Pull request merged**
